# Generated by Django 4.0.3 on 2022-04-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveIntegerField(choices=[(1, 'Water_Admin'), (2, 'Electric_Admin'), (3, 'Water_Reader'), (4, 'Water_Technician'), (5, 'Electric_Reader'), (6, 'Electric_Technician'), (7, 'Customer')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='role',
        ),
        migrations.AddField(
            model_name='account',
            name='roles',
            field=models.ManyToManyField(to='users.role'),
        ),
    ]
