# Generated by Django 4.0.3 on 2022-03-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_joined',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
