# Generated by Django 4.0.3 on 2022-04-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_remove_account_role_account_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='roles',
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('1', 'Water_Admin'), ('2', 'Electric_Admin'), ('3', 'Water_Reader'), ('4', 'Water_Technician'), ('5', 'Electric_Reader'), ('6', 'Electric_Technician'), ('7', 'Customer')], null=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
