# Generated by Django 4.0.3 on 2022-04-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_account_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_customer',
        ),
    ]
