# Generated by Django 4.0.3 on 2022-05-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_account_managers_alter_companyadmin_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyadmin',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
