# Generated by Django 4.0.3 on 2022-05-03 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_electricbalance_waterbalance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElectricBalance',
        ),
        migrations.DeleteModel(
            name='WaterBalance',
        ),
    ]
