# Generated by Django 4.0.3 on 2022-05-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_electricbalance_delete_waterbalance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyAdmin',
        ),
    ]
