# Generated by Django 4.0.3 on 2022-05-11 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_delete_companyadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[A-ZÁÉÍÓÚÑÇÄËÏÖÜa-zñáéíóúäëïöüç\\s]*$', 'Only letters allowed.')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[A-ZÁÉÍÓÚÑÇÄËÏÖÜa-zñáéíóúäëïöüç\\s]*$', 'Only letters allowed.')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='middle_name',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[A-ZÁÉÍÓÚÑÇÄËÏÖÜa-zñáéíóúäëïöüç\\s]*$', 'Only letters allowed.')]),
        ),
    ]
