# Generated by Django 4.0.3 on 2022-05-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_account_first_name_alter_account_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(blank=True, choices=[('water_reader', 'Water_Reader'), ('water_technician', 'Water_Technician'), ('electric_reader', 'Electric_Reader'), ('electric_technician', 'Electric_Technician'), ('customer', 'Customer')], max_length=20, null=True),
        ),
    ]
