# Generated by Django 4.0.3 on 2022-03-28 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricCustomer',
            fields=[
                ('meter_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
            options={
                'db_table': 'electric_customer',
            },
        ),
    ]
