# Generated by Django 4.0.3 on 2022-03-30 18:14

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterCustomer',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('meter_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'water_customer',
            },
            bases=('users.customer',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.TextField()),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('meter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.watercustomer')),
            ],
            options={
                'db_table': 'water_complain',
            },
        ),
        migrations.CreateModel(
            name='BillInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_reading', models.DecimalField(decimal_places=2, max_digits=50)),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=50)),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('meter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.watercustomer')),
            ],
            options={
                'db_table': 'billinfo',
            },
        ),
    ]
