# Generated by Django 4.0.3 on 2022-04-05 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_account_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterCustomer',
            fields=[
                ('meter_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
            options={
                'db_table': 'water_customer',
            },
        ),
        migrations.CreateModel(
            name='WaterComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.TextField()),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('meter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.watercustomer')),
            ],
            options={
                'db_table': 'water_complain',
            },
        ),
        migrations.CreateModel(
            name='WaterBillInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_reading', models.DecimalField(decimal_places=2, max_digits=50)),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=50)),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('meter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.watercustomer')),
            ],
            options={
                'db_table': 'waterbillinfo',
            },
        ),
    ]
