# Generated by Django 4.0.3 on 2022-04-05 21:26

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customer_is_customer'),
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='watercustomer',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='watercustomer',
            name='username',
        ),
        migrations.AddField(
            model_name='watercustomer',
            name='customer_ptr',
            field=models.OneToOneField(auto_created=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='users.customer'),
            preserve_default=False,
        ),
    ]
