# Generated by Django 3.2.9 on 2022-04-18 14:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customer_is_customer'),
        ('water', '0002_alter_watercustomer_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='watercustomer',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='watercustomer',
            name='customer_ptr',
        ),
        migrations.AddField(
            model_name='watercustomer',
            name='username',
            field=models.ForeignKey(default=django.utils.timezone.now, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
            preserve_default=False,
        ),
    ]
