# Generated by Django 4.0.4 on 2022-04-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0004_wateremployee'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wateremployee',
            table='water_employee',
        ),
    ]
