# Generated by Django 4.0.3 on 2022-05-03 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0006_alter_wateremployee_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbillinfo',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='waterbillinfo',
            name='status',
            field=models.CharField(default='not paid', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='watercomplain',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='watercomplain',
            name='status',
            field=models.CharField(default='not solved', max_length=50, null=True),
        ),
    ]
