# Generated by Django 4.0.3 on 2022-05-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0008_waterbalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterbillinfo',
            name='status',
        ),
        migrations.AddField(
            model_name='waterbillinfo',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='waterbillinfo',
            name='is_paid',
            field=models.BooleanField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='waterbillinfo',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('january', 'january'), ('february', 'february'), ('march', 'march'), ('april', 'april'), ('may', 'may'), ('june', 'june'), ('july', 'july'), ('august', 'august'), ('september', 'september'), ('october', 'october'), ('november', 'november'), ('december', 'december')], null=True),
        ),
        migrations.AddField(
            model_name='waterbillinfo',
            name='year',
            field=models.IntegerField(max_length=5, null=True),
        ),
    ]
