# Generated by Django 4.0.3 on 2022-05-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0009_remove_waterbillinfo_status_waterbillinfo_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbillinfo',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
