# Generated by Django 4.0.3 on 2022-05-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0010_alter_waterbillinfo_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbillinfo',
            name='month',
            field=models.CharField(blank=True, choices=[('january', 'january'), ('february', 'february'), ('march', 'march'), ('april', 'april'), ('may', 'may'), ('june', 'june'), ('july', 'july'), ('august', 'august'), ('september', 'september'), ('october', 'october'), ('november', 'november'), ('december', 'december')], max_length=50, null=True),
        ),
    ]
