# Generated by Django 4.0.3 on 2022-05-05 18:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_electricbalance_delete_waterbalance'),
        ('water', '0011_alter_waterbillinfo_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watercustomer',
            name='username',
        ),
        migrations.AddField(
            model_name='watercustomer',
            name='customer_ptr',
            field=models.OneToOneField(auto_created=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='users.customer'),
            preserve_default=False,
        ),
    ]
