# Generated by Django 4.0.3 on 2022-05-05 18:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_electricbalance_delete_waterbalance'),
        ('water', '0012_remove_watercustomer_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watercustomer',
            name='customer_ptr',
        ),
        migrations.AddField(
            model_name='watercustomer',
            name='username',
            field=models.ForeignKey(default=django.utils.timezone.now, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
            preserve_default=False,
        ),
    ]
