# Generated by Django 4.0.3 on 2022-05-09 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_electricbalance_delete_waterbalance'),
        ('water', '0013_remove_watercustomer_customer_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watercustomer',
            name='username',
            field=models.OneToOneField(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
    ]
