# Generated by Django 4.0.3 on 2022-05-10 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('water', '0014_alter_watercustomer_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('username', models.OneToOneField(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'water_reader',
            },
        ),
        migrations.CreateModel(
            name='WaterTechnician',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.OneToOneField(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'water_technician',
            },
        ),
        migrations.DeleteModel(
            name='WaterEmployee',
        ),
    ]
