# Generated by Django 4.0.3 on 2022-05-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0015_waterreader_watertechnician_delete_wateremployee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterreader',
            name='id',
        ),
        migrations.AlterField(
            model_name='waterreader',
            name='employee_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
