# Generated by Django 4.0.3 on 2022-05-10 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('water', '0016_remove_waterreader_id_alter_waterreader_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterreader',
            name='username',
        ),
        migrations.RemoveField(
            model_name='watertechnician',
            name='username',
        ),
        migrations.AddField(
            model_name='waterreader',
            name='account_ptr',
            field=models.OneToOneField(auto_created=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watertechnician',
            name='account_ptr',
            field=models.OneToOneField(auto_created=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='waterreader',
            name='employee_id',
            field=models.IntegerField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='watertechnician',
            name='employee_id',
            field=models.IntegerField(max_length=100, unique=True),
        ),
    ]
