# Generated by Django 4.0.3 on 2022-05-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0019_alter_waterreader_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterreader',
            name='employee_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='watertechnician',
            name='employee_id',
            field=models.IntegerField(null=True),
        ),
    ]
