# Generated by Django 4.0.3 on 2022-05-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0020_alter_waterreader_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbillinfo',
            name='prev_reading',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
