# Generated by Django 4.0.3 on 2022-05-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0021_alter_waterbillinfo_prev_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbillinfo',
            name='prev_reading',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
