# Generated by Django 4.0.4 on 2022-05-15 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0022_alter_waterbillinfo_prev_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbillinfo',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
