# Generated by Django 4.0.4 on 2022-05-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0023_waterbillinfo_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterbillinfo',
            name='created_at',
        ),
    ]
