# Generated by Django 4.0.3 on 2022-03-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Water',
            fields=[
                ('meter_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'water_customer',
            },
        ),
    ]
