# Generated by Django 4.0.3 on 2022-03-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_water_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=50, null=True)),
                ('m_name', models.CharField(max_length=50, null=True)),
                ('l_name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('house_no', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('age', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
