# Generated by Django 4.0.3 on 2022-03-26 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='username',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='water.customer'),
        ),
    ]
