# Generated by Django 4.0.3 on 2022-03-26 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0004_alter_water_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Water',
            new_name='WaterCustomer',
        ),
        migrations.CreateModel(
            name='WaterBillInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_reading', models.DecimalField(decimal_places=2, max_digits=50)),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=50)),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('meter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.watercustomer')),
            ],
            options={
                'db_table': 'billinfo',
            },
        ),
    ]
