# Generated by Django 4.0.3 on 2022-03-26 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0005_rename_water_watercustomer_waterbillinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.TextField()),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('meter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.watercustomer')),
            ],
            options={
                'db_table': 'water_complain',
            },
        ),
    ]
