# Generated by Django 4.0.3 on 2022-03-26 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('water', '0006_complain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watercustomer',
            name='username',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
