# Generated by Django 4.0.4 on 2022-04-18 19:28

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customer_is_customer'),
        ('electric', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricEmployee',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'electric_employee',
            },
            bases=('users.account',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
