# Generated by Django 4.0.3 on 2022-04-19 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electric', '0002_electricemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.TextField()),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('meter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electric.electriccustomer')),
            ],
            options={
                'db_table': 'electric_complain',
            },
        ),
        migrations.CreateModel(
            name='ElectricBillInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_reading', models.DecimalField(decimal_places=2, max_digits=50)),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=50)),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('meter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electric.electriccustomer')),
            ],
            options={
                'db_table': 'electricbillinfo',
            },
        ),
    ]
