# Generated by Django 4.0.3 on 2022-04-30 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electric', '0003_electriccomplain_electricbillinfo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='electricemployee',
            managers=[
            ],
        ),
    ]
